# Site settings
title: CSSclasses
email: contact@cssconf.eu
description: "CSSclasses is for beginners and experts alike: Using CSS as a simple and low-barrier entry language, we empower people to understand their browser and to learn how to experiment with code. Workshop and hackathon in one event."
baseurl: ""
url: "http://cssclasses.cssconf.eu"
twitter_username: cssclasses
github_username:  cssconf

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments